// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/jogador.proto
// Protobuf C++ Version: 5.27.3

#include "protobuf/jogador.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr Jogador::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : posicao_{},
        tamanho_{},
        vida_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR Jogador::Jogador(::_pbi::ConstantInitialized)
    : _impl_(::_pbi::ConstantInitialized()) {}
struct JogadorDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JogadorDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JogadorDefaultTypeInternal() {}
  union {
    Jogador _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JogadorDefaultTypeInternal _Jogador_default_instance_;
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_protobuf_2fjogador_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_protobuf_2fjogador_2eproto = nullptr;
const ::uint32_t
    TableStruct_protobuf_2fjogador_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::Jogador, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::Jogador, _impl_.posicao_),
        PROTOBUF_FIELD_OFFSET(::Jogador, _impl_.tamanho_),
        PROTOBUF_FIELD_OFFSET(::Jogador, _impl_.vida_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::Jogador)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::_Jogador_default_instance_._instance,
};
const char descriptor_table_protodef_protobuf_2fjogador_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\026protobuf/jogador.proto\"9\n\007Jogador\022\017\n\007p"
    "osicao\030\001 \003(\002\022\017\n\007tamanho\030\002 \003(\002\022\014\n\004vida\030\003 "
    "\001(\005b\006proto3"
};
static ::absl::once_flag descriptor_table_protobuf_2fjogador_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_protobuf_2fjogador_2eproto = {
    false,
    false,
    91,
    descriptor_table_protodef_protobuf_2fjogador_2eproto,
    "protobuf/jogador.proto",
    &descriptor_table_protobuf_2fjogador_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_protobuf_2fjogador_2eproto::offsets,
    file_level_enum_descriptors_protobuf_2fjogador_2eproto,
    file_level_service_descriptors_protobuf_2fjogador_2eproto,
};
// ===================================================================

class Jogador::_Internal {
 public:
};

Jogador::Jogador(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:Jogador)
}
inline PROTOBUF_NDEBUG_INLINE Jogador::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::Jogador& from_msg)
      : posicao_{visibility, arena, from.posicao_},
        tamanho_{visibility, arena, from.tamanho_},
        _cached_size_{0} {}

Jogador::Jogador(
    ::google::protobuf::Arena* arena,
    const Jogador& from)
    : ::google::protobuf::Message(arena) {
  Jogador* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.vida_ = from._impl_.vida_;

  // @@protoc_insertion_point(copy_constructor:Jogador)
}
inline PROTOBUF_NDEBUG_INLINE Jogador::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : posicao_{visibility, arena},
        tamanho_{visibility, arena},
        _cached_size_{0} {}

inline void Jogador::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.vida_ = {};
}
Jogador::~Jogador() {
  // @@protoc_insertion_point(destructor:Jogador)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void Jogador::SharedDtor() {
  ABSL_DCHECK(GetArena() == nullptr);
  _impl_.~Impl_();
}

const ::google::protobuf::MessageLite::ClassData*
Jogador::GetClassData() const {
  PROTOBUF_CONSTINIT static const ::google::protobuf::MessageLite::
      ClassDataFull _data_ = {
          {
              &_table_.header,
              nullptr,  // OnDemandRegisterArenaDtor
              nullptr,  // IsInitialized
              PROTOBUF_FIELD_OFFSET(Jogador, _impl_._cached_size_),
              false,
          },
          &Jogador::MergeImpl,
          &Jogador::kDescriptorMethods,
          &descriptor_table_protobuf_2fjogador_2eproto,
          nullptr,  // tracker
      };
  ::google::protobuf::internal::PrefetchToLocalCache(&_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_data_.tc_table);
  return _data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 0, 2> Jogador::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    &_Jogador_default_instance_._instance,
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::Jogador>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // repeated float posicao = 1;
    {::_pbi::TcParser::FastF32P1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(Jogador, _impl_.posicao_)}},
    // repeated float tamanho = 2;
    {::_pbi::TcParser::FastF32P1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Jogador, _impl_.tamanho_)}},
    // int32 vida = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Jogador, _impl_.vida_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Jogador, _impl_.vida_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated float posicao = 1;
    {PROTOBUF_FIELD_OFFSET(Jogador, _impl_.posicao_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // repeated float tamanho = 2;
    {PROTOBUF_FIELD_OFFSET(Jogador, _impl_.tamanho_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kPackedFloat)},
    // int32 vida = 3;
    {PROTOBUF_FIELD_OFFSET(Jogador, _impl_.vida_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void Jogador::Clear() {
// @@protoc_insertion_point(message_clear_start:Jogador)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.posicao_.Clear();
  _impl_.tamanho_.Clear();
  _impl_.vida_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

::uint8_t* Jogador::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Jogador)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated float posicao = 1;
  if (this->_internal_posicao_size() > 0) {
    target = stream->WriteFixedPacked(1, _internal_posicao(), target);
  }

  // repeated float tamanho = 2;
  if (this->_internal_tamanho_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_tamanho(), target);
  }

  // int32 vida = 3;
  if (this->_internal_vida() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt32ToArrayWithField<3>(
            stream, this->_internal_vida(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Jogador)
  return target;
}

::size_t Jogador::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Jogador)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(reinterpret_cast<const void*>(this));
  // repeated float posicao = 1;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_posicao_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // repeated float tamanho = 2;
  {
    std::size_t data_size = std::size_t{4} *
        ::_pbi::FromIntSize(this->_internal_tamanho_size())
    ;
    std::size_t tag_size = data_size == 0
        ? 0
        : 1 + ::_pbi::WireFormatLite::Int32Size(
                            static_cast<int32_t>(data_size))
    ;
    total_size += tag_size + data_size;
  }
  // int32 vida = 3;
  if (this->_internal_vida() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
        this->_internal_vida());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}


void Jogador::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Jogador*>(&to_msg);
  auto& from = static_cast<const Jogador&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:Jogador)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_posicao()->MergeFrom(from._internal_posicao());
  _this->_internal_mutable_tamanho()->MergeFrom(from._internal_tamanho());
  if (from._internal_vida() != 0) {
    _this->_impl_.vida_ = from._impl_.vida_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Jogador::CopyFrom(const Jogador& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Jogador)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Jogador::InternalSwap(Jogador* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.posicao_.InternalSwap(&other->_impl_.posicao_);
  _impl_.tamanho_.InternalSwap(&other->_impl_.tamanho_);
        swap(_impl_.vida_, other->_impl_.vida_);
}

::google::protobuf::Metadata Jogador::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_protobuf_2fjogador_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
