// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: protobuf/jogador.proto
// Protobuf C++ Version: 5.27.3

#ifndef GOOGLE_PROTOBUF_INCLUDED_protobuf_2fjogador_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_protobuf_2fjogador_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027003
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_protobuf_2fjogador_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_protobuf_2fjogador_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_protobuf_2fjogador_2eproto;
class Jogador;
struct JogadorDefaultTypeInternal;
extern JogadorDefaultTypeInternal _Jogador_default_instance_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Jogador final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Jogador) */ {
 public:
  inline Jogador() : Jogador(nullptr) {}
  ~Jogador() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Jogador(
      ::google::protobuf::internal::ConstantInitialized);

  inline Jogador(const Jogador& from) : Jogador(nullptr, from) {}
  inline Jogador(Jogador&& from) noexcept
      : Jogador(nullptr, std::move(from)) {}
  inline Jogador& operator=(const Jogador& from) {
    CopyFrom(from);
    return *this;
  }
  inline Jogador& operator=(Jogador&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Jogador& default_instance() {
    return *internal_default_instance();
  }
  static inline const Jogador* internal_default_instance() {
    return reinterpret_cast<const Jogador*>(
        &_Jogador_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Jogador& a, Jogador& b) { a.Swap(&b); }
  inline void Swap(Jogador* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Jogador* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Jogador* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<Jogador>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Jogador& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Jogador& from) { Jogador::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(Jogador* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "Jogador"; }

 protected:
  explicit Jogador(::google::protobuf::Arena* arena);
  Jogador(::google::protobuf::Arena* arena, const Jogador& from);
  Jogador(::google::protobuf::Arena* arena, Jogador&& from) noexcept
      : Jogador(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPosicaoFieldNumber = 1,
    kTamanhoFieldNumber = 2,
    kVidaFieldNumber = 3,
  };
  // repeated float posicao = 1;
  int posicao_size() const;
  private:
  int _internal_posicao_size() const;

  public:
  void clear_posicao() ;
  float posicao(int index) const;
  void set_posicao(int index, float value);
  void add_posicao(float value);
  const ::google::protobuf::RepeatedField<float>& posicao() const;
  ::google::protobuf::RepeatedField<float>* mutable_posicao();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_posicao() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_posicao();

  public:
  // repeated float tamanho = 2;
  int tamanho_size() const;
  private:
  int _internal_tamanho_size() const;

  public:
  void clear_tamanho() ;
  float tamanho(int index) const;
  void set_tamanho(int index, float value);
  void add_tamanho(float value);
  const ::google::protobuf::RepeatedField<float>& tamanho() const;
  ::google::protobuf::RepeatedField<float>* mutable_tamanho();

  private:
  const ::google::protobuf::RepeatedField<float>& _internal_tamanho() const;
  ::google::protobuf::RepeatedField<float>* _internal_mutable_tamanho();

  public:
  // int32 vida = 3;
  void clear_vida() ;
  ::int32_t vida() const;
  void set_vida(::int32_t value);

  private:
  ::int32_t _internal_vida() const;
  void _internal_set_vida(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Jogador)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_Jogador_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Jogador& from_msg);
    ::google::protobuf::RepeatedField<float> posicao_;
    ::google::protobuf::RepeatedField<float> tamanho_;
    ::int32_t vida_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_protobuf_2fjogador_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Jogador

// repeated float posicao = 1;
inline int Jogador::_internal_posicao_size() const {
  return _internal_posicao().size();
}
inline int Jogador::posicao_size() const {
  return _internal_posicao_size();
}
inline void Jogador::clear_posicao() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.posicao_.Clear();
}
inline float Jogador::posicao(int index) const {
  // @@protoc_insertion_point(field_get:Jogador.posicao)
  return _internal_posicao().Get(index);
}
inline void Jogador::set_posicao(int index, float value) {
  _internal_mutable_posicao()->Set(index, value);
  // @@protoc_insertion_point(field_set:Jogador.posicao)
}
inline void Jogador::add_posicao(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_posicao()->Add(value);
  // @@protoc_insertion_point(field_add:Jogador.posicao)
}
inline const ::google::protobuf::RepeatedField<float>& Jogador::posicao() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Jogador.posicao)
  return _internal_posicao();
}
inline ::google::protobuf::RepeatedField<float>* Jogador::mutable_posicao()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Jogador.posicao)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_posicao();
}
inline const ::google::protobuf::RepeatedField<float>&
Jogador::_internal_posicao() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.posicao_;
}
inline ::google::protobuf::RepeatedField<float>* Jogador::_internal_mutable_posicao() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.posicao_;
}

// repeated float tamanho = 2;
inline int Jogador::_internal_tamanho_size() const {
  return _internal_tamanho().size();
}
inline int Jogador::tamanho_size() const {
  return _internal_tamanho_size();
}
inline void Jogador::clear_tamanho() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.tamanho_.Clear();
}
inline float Jogador::tamanho(int index) const {
  // @@protoc_insertion_point(field_get:Jogador.tamanho)
  return _internal_tamanho().Get(index);
}
inline void Jogador::set_tamanho(int index, float value) {
  _internal_mutable_tamanho()->Set(index, value);
  // @@protoc_insertion_point(field_set:Jogador.tamanho)
}
inline void Jogador::add_tamanho(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _internal_mutable_tamanho()->Add(value);
  // @@protoc_insertion_point(field_add:Jogador.tamanho)
}
inline const ::google::protobuf::RepeatedField<float>& Jogador::tamanho() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:Jogador.tamanho)
  return _internal_tamanho();
}
inline ::google::protobuf::RepeatedField<float>* Jogador::mutable_tamanho()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:Jogador.tamanho)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_tamanho();
}
inline const ::google::protobuf::RepeatedField<float>&
Jogador::_internal_tamanho() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.tamanho_;
}
inline ::google::protobuf::RepeatedField<float>* Jogador::_internal_mutable_tamanho() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.tamanho_;
}

// int32 vida = 3;
inline void Jogador::clear_vida() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vida_ = 0;
}
inline ::int32_t Jogador::vida() const {
  // @@protoc_insertion_point(field_get:Jogador.vida)
  return _internal_vida();
}
inline void Jogador::set_vida(::int32_t value) {
  _internal_set_vida(value);
  // @@protoc_insertion_point(field_set:Jogador.vida)
}
inline ::int32_t Jogador::_internal_vida() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vida_;
}
inline void Jogador::_internal_set_vida(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vida_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_protobuf_2fjogador_2eproto_2epb_2eh
